name: Project #2. Difference calc
run-name: ${{ github.actor }} is testing Project #2. Difference Cals 🚀

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: echo "✅ Python has been successfully set up."

      - name: Install dependencies
        run: |
          pip install uv
          make install
      - run: echo "✅ Dependencies have been successfully installed."
          
      - name: Run linter and pytest
        run: |
          make lint
          make test
      - run: echo "✅ Linter and pytest check - done."
      
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
      - run: echo "✅ Test and publish code coverage - done."
